/** @type {import('sequelize-cli').Migration} */
const bcrypt = require('bcrypt');
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Categories', [
      {
        catName: 'HTML',
        themeId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'Атрибуты',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'Селекторы',
        themeId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'CSS',
        themeId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'Псевдоэлементы',
        themeId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'Flex',
        themeId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'JavaScript',
        themeId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'Классы',
        themeId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        catName: 'Методы массивов',
        themeId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
    await queryInterface.bulkInsert('Questions', [
      {
        questions: 'Какое расширение имеют файлы HTML?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для создания заголовка первого уровня?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой тег используется для создания ссылки?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для создания списка с маркированными пунктами?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для создания таблицы?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для вставки изображения?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для создания абзаца текста?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для выделения жирного текста?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для создания формы ввода текста?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой тег используется для создания кнопки?',
        catId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=lEt1JS0e8h4&ab_channel=%D0%9F%D0%B8%D0%BA%D1%81%D0%B5%D0%BB%D1%8C-%D1%88%D0%BA%D0%BE%D0%BB%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D0%B4%D0%BB%D1%8F%D0%B4%D0%B5%D1%82%D0%B5%D0%B9',
      },
      {
        questions: 'Какой HTML-тег используется для создания таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой атрибут используется для объединения нескольких ячеек в одну в таблице?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой CSS-свойство используется для задания цвета фона ячейки таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой CSS-свойство используется для задания ширины границы ячейки таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой CSS-селектор используется для выбора всех ячеек таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какая единица измерения используется для задания высоты строки таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions:
          'Какой CSS-свойство используется для выравнивания текста в ячейке таблицы по горизонтали?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой HTML-тег используется для создания заголовка таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой CSS-свойство используется для задания отступов внутри ячейки таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions: 'Какой атрибут используется для задания границы таблицы?',
        catId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=8bp5nCL7Uu0',
      },
      {
        questions:
          'Какой псевдоэлемент используется для добавления контента перед содержимым элемента?',
        catId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=C40ePbYJxmM&ab_channel=webDev',
      },
      {
        questions:
          'Какой псевдоэлемент используется для добавления контента после содержимого элемента?',
        catId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=C40ePbYJxmM&ab_channel=webDev',
      },
      {
        questions: 'Какой псевдоэлемент используется для выбора первого символа внутри элемента?',
        catId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=C40ePbYJxmM&ab_channel=webDev',
      },
      {
        questions:
          'Какой псевдоэлемент используется для выбора последнего символа внутри элемента?',
        catId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=C40ePbYJxmM&ab_channel=webDev',
      },
      {
        questions: 'Какой псевдоэлемент используется для выбора первого дочернего элемента?',
        catId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=C40ePbYJxmM&ab_channel=webDev',
      },
      {
        questions: 'Какое свойство в CSS используется для создания flex-контейнера?',
        catId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=eVZEwEQg4pg&ab_channel=UlbiTV’',
      },
      {
        questions:
          'Какое свойство в CSS используется для задания направления расположения элементов в flex-контейнере?',
        catId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=eVZEwEQg4pg&ab_channel=UlbiTV’',
      },
      {
        questions:
          'Какое свойство в CSS используется для установки пространства между элементами внутри flex-контейнера?',
        catId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=eVZEwEQg4pg&ab_channel=UlbiTV’',
      },
      {
        questions:
          'Какое свойство в CSS используется для указания, как будут распределены свободное пространство и переполнение элементов внутри flex-контейнера?',
        catId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=eVZEwEQg4pg&ab_channel=UlbiTV’',
      },
      {
        questions:
          'Какое свойство в CSS используется для выравнивания элементов вдоль главной оси flex-контейнера?',
        catId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        video: 'https://www.youtube.com/watch?v=eVZEwEQg4pg&ab_channel=UlbiTV’',
      },
      {
        questions: 'Что такое класс в JavaScript?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Как создать экземпляр класса в JavaScript?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Что такое конструктор класса?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Как добавить метод в класс в JavaScript?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Что такое наследование классов в JavaScript?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Как создать дочерний класс в JavaScript?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Как вызвать метод родительского класса из дочернего класса?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Что такое полиморфизм в контексте классов в JavaScript?',
        catId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Что такое статические методы в классах в JavaScript?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Что такое инкапсуляция в контексте классов в JavaScript?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=uLY9GXGMXaA&ab_channel=%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BB%D0%B5%D0%BD%D0%9C%D0%B8%D0%BD%D0%B8%D0%BD',
      },
      {
        questions: 'Какой метод массива используется для добавления элемента в конец массива?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions: 'Какой метод массива используется для удаления последнего элемента массива?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions: 'dsffdsdsf',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions: 'Какой метод массива используется для объединения двух массивов в один?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions:
          'Какой метод массива используется для проверки наличия определенного элемента в массиве?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions:
          'Какой метод массива используется для сортировки элементов массива в порядке возрастания?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions:
          'Какой метод массива используется для поиска индекса определенного элемента в массиве?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions:
          'Какой метод массива используется для преобразования каждого элемента массива и создания нового массива с результатами?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions:
          'Какой метод массива используется для фильтрации элементов массива с помощью заданного условия?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions: 'Какой метод массива используется для получения первого элемента массива?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
      {
        questions: 'Какой метод массива используется для получения количества элементов в массиве?',
        catId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        video:
          'https://www.youtube.com/watch?v=IpsoddCpXUY&ab_channel=%D0%A4%D1%80%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D0%B4%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC%D0%B8%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D0%BC%D0%B8nullnull',
      },
    ]);
    await queryInterface.bulkInsert(
      'Answers',
      [
        {
          answers: '.txt',
          isCorrect: false,
          qId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '.html',
          isCorrect: true,
          qId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '.css',
          isCorrect: false,
          qId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '.js',
          isCorrect: false,
          qId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answers: '<h1>',
          isCorrect: true,
          qId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<h2>',
          isCorrect: false,
          qId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<h3>',
          isCorrect: false,
          qId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<h4>',
          isCorrect: false,
          qId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<a>',
          isCorrect: true,
          qId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<p>',
          isCorrect: false,
          qId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<div>',
          isCorrect: false,
          qId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<span>',
          isCorrect: false,
          qId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answers: '<ul>',
          isCorrect: false,
          qId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<ol>',
          isCorrect: true,
          qId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<li>',
          isCorrect: false,
          qId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<dl>',
          isCorrect: false,
          qId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<table>',
          isCorrect: true,
          qId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<tr>',
          isCorrect: false,
          qId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<td>',
          isCorrect: false,
          qId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<th>',
          isCorrect: false,
          qId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<img>',
          isCorrect: true,
          qId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<div>',
          isCorrect: false,
          qId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<span>',
          isCorrect: false,
          qId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<p>',
          isCorrect: false,
          qId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<p>',
          isCorrect: true,
          qId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<h1>',
          isCorrect: false,
          qId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<a>',
          isCorrect: false,
          qId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<span>',
          isCorrect: false,
          qId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<strong>',
          isCorrect: true,
          qId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<em>',
          isCorrect: false,
          qId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<b>',
          isCorrect: false,
          qId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<i>',
          isCorrect: false,
          qId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<input>',
          isCorrect: true,
          qId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<form>',
          isCorrect: false,
          qId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<button>',
          isCorrect: false,
          qId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<label>',
          isCorrect: true,
          qId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<button>',
          isCorrect: true,
          qId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<input>',
          isCorrect: false,
          qId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<form>',
          isCorrect: false,
          qId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '<label>',
          isCorrect: false,
          qId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'able',
          isCorrect: true,
          qId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'div',
          isCorrect: false,
          qId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'form',
          isCorrect: false,
          qId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'span',
          isCorrect: false,
          qId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'colspan',
          isCorrect: true,
          qId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'rowspan',
          isCorrect: false,
          qId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'merge',
          isCorrect: false,
          qId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'cellspan',
          isCorrect: false,
          qId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'color',
          isCorrect: false,
          qId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'font-size',
          isCorrect: false,
          qId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'background-color',
          isCorrect: true,
          qId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'border-color',
          isCorrect: false,
          qId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'border-width',
          isCorrect: true,
          qId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'padding',
          isCorrect: false,
          qId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'margin',
          isCorrect: false,
          qId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'width',
          isCorrect: false,
          qId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          answers: '.table',
          isCorrect: false,
          qId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '#table',
          isCorrect: false,
          qId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'table td',
          isCorrect: true,
          qId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'table th',
          isCorrect: false,
          qId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'px',
          isCorrect: true,
          qId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'em',
          isCorrect: false,
          qId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '%',
          isCorrect: false,
          qId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'rem',
          isCorrect: false,
          qId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'text-align',
          isCorrect: true,
          qId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'vertical-align',
          isCorrect: false,
          qId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'align',
          isCorrect: false,
          qId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'justify-content',
          isCorrect: false,
          qId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'table',
          isCorrect: false,
          qId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'tr',
          isCorrect: false,
          qId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'td',
          isCorrect: false,
          qId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'th',
          isCorrect: true,
          qId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'padding',
          isCorrect: true,
          qId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'margin',
          isCorrect: false,
          qId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'border-spacing',
          isCorrect: false,
          qId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'spacing',
          isCorrect: false,
          qId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'outline',
          isCorrect: false,
          qId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'border',
          isCorrect: true,
          qId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'box-shadow',
          isCorrect: false,
          qId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'border-style',
          isCorrect: false,
          qId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::before',
          isCorrect: true,
          qId: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::after',
          isCorrect: false,
          qId: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::content',
          isCorrect: false,
          qId: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::prepend',
          isCorrect: false,
          qId: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::before',
          isCorrect: false,
          qId: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::after',
          isCorrect: true,
          qId: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::content',
          isCorrect: false,
          qId: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::append',
          isCorrect: false,
          qId: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-char',
          isCorrect: false,
          qId: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-letter',
          isCorrect: true,
          qId: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-child',
          isCorrect: false,
          qId: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-of-type',
          isCorrect: false,
          qId: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::last-char',
          isCorrect: false,
          qId: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::last-child',
          isCorrect: false,
          qId: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::last-letter',
          isCorrect: true,
          qId: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::last-of-type',
          isCorrect: false,
          qId: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-of-type',
          isCorrect: false,
          qId: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-element',
          isCorrect: false,
          qId: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-child',
          isCorrect: true,
          qId: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: '::first-descendant',
          isCorrect: false,
          qId: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'display: block',
          isCorrect: false,
          qId: 26,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'display: flex',
          isCorrect: true,
          qId: 26,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'position: relative',
          isCorrect: false,
          qId: 26,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'float: none',
          isCorrect: false,
          qId: 26,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'Описание объекта со свойствами и методами.',
          isCorrect: true,
          qId: 31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'Массив данных.',
          isCorrect: false,
          qId: 31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'Функция для выполнения операций с данными.',
          isCorrect: false,
          qId: 31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'HTML-элемент.',
          isCorrect: false,
          qId: 31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'add()',
          isCorrect: false,
          qId: 41,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'push()',
          isCorrect: true,
          qId: 41,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'append()',
          isCorrect: false,
          qId: 41,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          answers: 'insert()',
          isCorrect: false,
          qId: 41,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );

    await queryInterface.bulkInsert('Users', [
      {
        name: 'Вазген',
        hashpass: await bcrypt.hash('123', 10),
        createdAt: new Date(),
        updatedAt: new Date(),
        email: '1@1.ru',
        phone: '1',
      },
    ]);

    await queryInterface.bulkInsert('Statistics', [
      {
        userId: 1,
        qId: 1,
        createdAt: new Date(),
        status: true,
        updatedAt: new Date(),
      },
      {
        userId: 1,
        qId: 2,
        createdAt: new Date(),
        status: false,
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
